### ISSUE TITLE
Failed to execute script 'VideoDownload' due to unhandled exception!

### ISSUE THREAD

**Issue by swassglass** [jshackles/CloneHeroVideoDownloader#1]
I  keep getting the following error. Just thought I would share. It was working fine on my 600 song library, but then I added way more and now getting this problem. 

PS C:\Program Files\Clone Hero> .\VideoDownload.exe
  5%|███▋                                                                       | 163/3366 [00:07<02:25, 22.01videos/s]
Traceback (most recent call last):
  File "VideoDownload.py", line 48, in <module>
  File "configparser.py", line 1205, in set
  File "configparser.py", line 903, in set
configparser.NoSectionError: No section: 'song'
[24464] Failed to execute script 'VideoDownload' due to unhandled exception!

**Comment by crobibero** [comment]
I am also getting this error. The script doesn't output the path that it's currently running on so I don't know the issue folder.

**Comment by stripedew** [comment]
Old post but thought I'd update - I forked this and updated it to work again.
https://github.com/stripedew/CloneHeroVideoDownloader/

@swassglass @crobibero
